LANG_GRAMMARS = {
    # 主流编程语言
    'python': 'https://github.com/tree-sitter/tree-sitter-python',
    'javascript': 'https://github.com/tree-sitter/tree-sitter-javascript',
    'typescript': 'https://github.com/tree-sitter/tree-sitter-typescript',
    'java': 'https://github.com/tree-sitter/tree-sitter-java',
    'c': 'https://github.com/tree-sitter/tree-sitter-c',
    'cpp': 'https://github.com/tree-sitter/tree-sitter-cpp',
    'csharp': 'https://github.com/tree-sitter/tree-sitter-c-sharp',
    'go': 'https://github.com/tree-sitter/tree-sitter-go',
    'rust': 'https://github.com/tree-sitter/tree-sitter-rust',
    'swift': 'https://github.com/tree-sitter/tree-sitter-swift',
    'kotlin': 'https://github.com/fwcd/tree-sitter-kotlin',
    'ruby': 'https://github.com/tree-sitter/tree-sitter-ruby',
    'php': 'https://github.com/tree-sitter/tree-sitter-php',
    'perl': 'https://github.com/ganezdragon/tree-sitter-perl',
    'lua': 'https://github.com/MunifTanjim/tree-sitter-lua',
    'dart': 'https://github.com/UserNobody14/tree-sitter-dart',
    'scala': 'https://github.com/tree-sitter/tree-sitter-scala',
    'haskell': 'https://github.com/tree-sitter/tree-sitter-haskell',
    'r': 'https://github.com/r-lib/tree-sitter-r',

    # 脚本与系统语言
    'bash': 'https://github.com/tree-sitter/tree-sitter-bash',
    'powershell': 'https://github.com/tree-sitter/tree-sitter-powershell',
    'make': 'https://github.com/alemuller/tree-sitter-make',
    'nix': 'https://github.com/nix-community/tree-sitter-nix',

    # Web / 标记语言
    'html': 'https://github.com/tree-sitter/tree-sitter-html',
    'css': 'https://github.com/tree-sitter/tree-sitter-css',
    'scss': 'https://github.com/serenadeai/tree-sitter-scss',
    'json': 'https://github.com/tree-sitter/tree-sitter-json',
    'yaml': 'https://github.com/ikatyang/tree-sitter-yaml',
    'toml': 'https://github.com/tree-sitter/tree-sitter-toml',
    'xml': 'https://github.com/tree-sitter/tree-sitter-xml',
    'markdown': 'https://github.com/ikatyang/tree-sitter-markdown',

    # 数据与查询语言
    'sql': 'https://github.com/DerekStride/tree-sitter-sql',
    'graphql': 'https://github.com/bkegley/tree-sitter-graphql',
    'jsonnet': 'https://github.com/sourcegraph/tree-sitter-jsonnet',

    # 配置与构建
    'dockerfile': 'https://github.com/camdencheek/tree-sitter-dockerfile',
    'cmake': 'https://github.com/uyha/tree-sitter-cmake',
    'ini': 'https://github.com/justinmk/tree-sitter-ini',

    # 特殊语言
    'latex': 'https://github.com/latex-lsp/tree-sitter-latex',
    'verilog': 'https://github.com/tree-sitter/tree-sitter-verilog',
    'vhdl': 'https://github.com/alemuller/tree-sitter-vhdl',
    'assembly': 'https://github.com/tree-sitter/tree-sitter-asm',
    'wasm': 'https://github.com/wasm-lsp/tree-sitter-wat',
}
LANG_FILE_EXTENSIONS = {
    'python': ['.py', '.pyw'],  
    'javascript': ['.js', '.mjs', '.cjs'],
    'typescript': ['.ts', '.tsx'],
    'java': ['.java'],      
    'c': ['.c', '.h'],

    'cpp': ['.cpp', '.cc', '.cxx', '.hpp', '.hh', '.hxx', '.h'],
    'csharp': ['.cs'],
    'go': ['.go'],
    'rust': ['.rs'],
    'swift': ['.swift'],
    'kotlin': ['.kt', '.kts'],
    'ruby': ['.rb'],
    'php': ['.php', '.phtml', '.php3', '.php4', '.php5', '.phps'],
    'perl': ['.pl', '.pm'],
    'lua': ['.lua'],
    'dart': ['.dart'],
    'scala': ['.scala'],
    'haskell': ['.hs', '.lhs'],
    'r': ['.r', '.R'],
    'bash': ['.sh', '.bash'],
    'powershell': ['.ps1', '.psm1'],
    'make': ['Makefile', 'makefile'],
    'nix': ['.nix'],
    'html': ['.html', '.htm'],
    'css': ['.css'],
    'scss': ['.scss'],
    'json': ['.json'],
    'yaml': ['.yaml', '.yml'],
    'toml': ['.toml'],  
    'xml': ['.xml', '.xsl', '.xslt', '.svg'],
    'markdown': ['.md', '.markdown'],
    'sql': ['.sql'],
    'graphql': ['.graphql', '.gql'],
    'jsonnet': ['.jsonnet', '.libsonnet'],
    'dockerfile': ['Dockerfile', 'dockerfile'],
    'cmake': ['CMakeLists.txt', '.cmake'],
    'ini': ['.ini', '.cfg', '.conf'],
    'latex': ['.tex', '.ltx'],
    'verilog': ['.v', '.vh', '.sv', '.svh'],    
    'vhdl': ['.vhd', '.vhdl'],
    'assembly': ['.asm', '.s'],
    'wasm': ['.wat', '.wasm'],
}

TREE_SITTER_QUERIES = {
    'python': {
        'functions': '(function_definition name: (identifier) @function.name)',
        'classes': '(class_definition name: (identifier) @class.name)',
        'calls': '(call function: (identifier) @function.call)',
        'variables': '(assignment left: (identifier) @var.name)',
        'imports': '(import_from_statement module_name: (dotted_name) @import.module)',
    },
    'javascript': {
        'functions': '(function_declaration name: (identifier) @function.name)',
        'classes': '(class_declaration name: (identifier) @class.name)',
        'calls': '(call_expression function: (identifier) @function.call)',
        'variables': '(variable_declarator name: (identifier) @var.name)',
        'imports': '(import_clause (import_specifier name: (identifier) @import.name))',
    },
    'typescript': {
        'functions': '(function_declaration name: (identifier) @function.name)',
        'classes': '(class_declaration name: (identifier) @class.name)',
        'calls': '(call_expression function: (identifier) @function.call)',
        'variables': '(variable_declaration name: (identifier) @var.name)',
        'imports': '(import_clause (import_specifier name: (identifier) @import.name))',
    },
    'java': {
        'functions': '(method_declaration name: (identifier) @function.name)',
        'classes': '(class_declaration name: (identifier) @class.name)',
        'calls': '(method_invocation name: (identifier) @function.call)',
        'variables': '(variable_declarator name: (identifier) @var.name)',
        'imports': '(import_declaration name: (scoped_identifier) @import.name)',
    },
    'cpp': {
        'functions': '(function_definition declarator: (function_declarator declarator: (identifier) @function.name))',
        'classes': '(class_specifier name: (type_identifier) @class.name)',
        'calls': '(call_expression function: (identifier) @function.call)',
        'variables': '(init_declarator declarator: (identifier) @var.name)',
        'imports': '(preproc_include path: (string_literal) @import.path)',
    },
    'c': {
        'functions': '(function_definition declarator: (function_declarator declarator: (identifier) @function.name))',
        'calls': '(call_expression function: (identifier) @function.call)',
        'variables': '(init_declarator declarator: (identifier) @var.name)',
        'imports': '(preproc_include path: (string_literal) @import.path)',
    },
    'go': {
        'functions': '(function_declaration name: (identifier) @function.name)',
        'methods': '(method_declaration name: (field_identifier) @function.name)',
        'classes': '(type_declaration name: (type_identifier) @class.name)',
        'calls': '(call_expression function: (selector_expression field: (field_identifier) @function.call))',
        'variables': '(short_var_declaration left: (identifier) @var.name)',
        'imports': '(import_spec path: (interpreted_string_literal) @import.path)',
    },
    'rust': {
        'functions': '(function_item name: (identifier) @function.name)',
        'impls': '(impl_item type: (type_identifier) @class.name)',
        'calls': '(call_expression function: (identifier) @function.call)',
        'variables': '(let_declaration pattern: (identifier) @var.name)',
        'imports': '(use_declaration (scoped_identifier) @import.name)',
    },
    'php': {
        'functions': '(function_definition name: (name) @function.name)',
        'classes': '(class_declaration name: (name) @class.name)',
        'calls': '(function_call_expression function: (name) @function.call)',
        'variables': '(assignment left: (variable_name) @var.name)',
        'imports': '(namespace_use_clause (namespace_name) @import.name)',
    },
    'ruby': {
        'functions': '(method name: (identifier) @function.name)',
        'classes': '(class name: (constant) @class.name)',
        'calls': '(call method: (identifier) @function.call)',
        'variables': '(assignment left: (identifier) @var.name)',
        'imports': '(require (string) @import.path)',
    },
    'swift': {
        'functions': '(function_declaration name: (identifier) @function.name)',
        'classes': '(class_declaration name: (identifier) @class.name)',
        'calls': '(call_expression function: (identifier) @function.call)',
        'variables': '(variable_declaration pattern: (identifier) @var.name)',
        'imports': '(import_declaration path: (identifier) @import.module)',
    },
    'csharp': {
        'functions': '(method_declaration name: (identifier) @function.name)',
        'classes': '(class_declaration name: (identifier) @class.name)',
        'calls': '(invocation_expression function: (identifier) @function.call)',
        'variables': '(variable_declarator name: (identifier) @var.name)',
        'imports': '(using_directive name: (qualified_name) @import.name)',
    },
    'bash': {
        'functions': '(function_definition name: (word) @function.name)',
        'calls': '(command name: (word) @function.call)',
        'variables': '(variable_assignment name: (word) @var.name)',
        'imports': '(source_command argument: (word) @import.path)',
    },
    'lua': {
        'functions': '(function_declaration name: (identifier) @function.name)',
        'calls': '(function_call name: (identifier) @function.call)',
        'variables': '(assignment variable_list: (identifier) @var.name)',
        'imports': '(function_call name: (identifier) @import.name)',
    },
    'sql': {
        'functions': '(create_function_statement name: (identifier) @function.name)',
        'calls': '(function_call function: (identifier) @function.call)',
        'variables': '(assignment_expression left: (identifier) @var.name)',
    },
    'json': {},
    'yaml': {},
    'html': {
        'tags': '(start_tag (tag_name) @tag.name)',
    },
    'css': {
        'classes': '(class_selector (identifier) @class.name)',
    },
    'markdown': {
        'headings': '(atx_heading (heading_content) @heading.text)',
    },
}
